[LM-10753] Profile changes to accommodate user created post and comment lists.
LikeMindsCommunity/likeminds-feed-flutter pull request #32
Opened 2024-03-13 21:20 UTC by AnujLM

2024-03-14 08:21 UTC, TyagiLikeMinds requested changes

2024-03-14 08:21 UTC, TyagiLikeMinds commented on packages/integration/lib/src/widgets/user/saved_post_listview.dart
> +            rebuildPostWidget.value = !rebuildPostWidget.value;
use bloc to update post data locally

2024-03-14 08:21 UTC, TyagiLikeMinds commented on packages/integration/lib/src/widgets/user/saved_post_listview.dart
> +          rebuildPostWidget.value = !rebuildPostWidget.value;
use bloc to update post data locally

2024-03-14 08:21 UTC, TyagiLikeMinds commented on packages/integration/lib/src/widgets/user/user_created_comment_listview.dart
> +    _userCreatedCommentBloc.add(
can remove _page key and this event as well, adding a page request listener will do the job

2024-03-14 08:21 UTC, TyagiLikeMinds commented on packages/integration/lib/src/widgets/user/user_created_comment_listview.dart
> +        _userCreatedCommentBloc.add(
use pageKey instead of page

2024-03-14 08:21 UTC, TyagiLikeMinds commented on packages/integration/lib/src/widgets/user/user_created_comment_listview.dart
> +      _pagingController.appendPage(state.comments, _page + 1);
send the pagekey in state that you received in the event and use that pageKey here

2024-03-14 08:21 UTC, TyagiLikeMinds commented on packages/integration/lib/src/widgets/user/user_created_comment_listview.dart
> +
update post data locally using bloc

2024-03-18 09:15 UTC, AnujLM commented on packages/integration/lib/src/bloc/user_meta/user_meta_bloc.dart
> +        add(LMFeedUserMetaGetEvent(uuid: event.user.uuid));
Data is not returned in that response, only getting a success message

2024-03-18 09:17 UTC, AnujLM commented on packages/integration/lib/src/views/activity/notification_screen.dart
> +  Widget _defCustomWidget() {
in this case 'Notification' text heading is not in the appbar, instead they are expecting to show this on the top of the list, through this custom widget we can give the ability to add any widget on top of notification list,

2024-03-18 11:59 UTC, TyagiLikeMinds approved these changes

2024-03-19 05:52 UTC, merged